#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - xubuntu-core
  - x2goserver
  - x2goserver-xsession
  - x2goserver-desktopsharing
  - firefox
  - flatpak
    
#snap:
#  commands:
#    - ['install', 'intellij-idea-ultimate']

runcmd:
  - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - flatpak install -y flathub com.anydesk.Anydesk
    

# TODO
# intellij
# git
# lg
#
