#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - xubuntu-core
  - tigervnc-standalone-server
  - anydesk

write_files:
  - content: |
      #!/bin/sh
      unset SESSION_MANAGER
      unset DBUS_SESSION_BUS_ADDRESS
      exec startxfce4
    path: /opt/xstart
    permissions: '0775'

runcmd:
  - service anydesk stop  
  - runuser -l gregor -c 'mkdir /home/gregor/.vnc'
  - cp /opt/xstart /home/gregor/.vnc/xstart
  - chown gregor:gregor /home/gregor/.vnc/xstart
  - runuser -l gregor -c 'printf "gregor\ngregor\n\n" | vncserver'

apt:
  preserve_sources_list: true
  sources:
    anydesk-stable.list:
      source: "deb http://deb.anydesk.com/ all main"
      # Key from https://keys.anydesk.com/repos/DEB-GPG-KEY
      key: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----

        mQENBFo4y64BCADDrIpJwfhOueAvVcbsziRiIBEKg1Bkz5ozDvO9dmU6bInCSesh
        IDBzp2yeipg1ccwm5Zj/ADbHJn3BGL/potZmn40fGcuBoqqIVzAQY+bOvd52g4m5
        zEVwql8RWsKCDL/G8FDhI9aOReGq88oWQCoukXy2qWFkRWYZ0XbKXdc8Af7+ZkkY
        3zcQ7QOwQq7xgmniCsmVltcRax4aoy2fDR4q+QMdlHlrdVGHycZd8H1GbpI0WvWg
        z9GV63Mhc0uWRimNrv5yJexyPRaodUu8Quo+AVDxGoplmY34M8DZuylXDn8U9yK5
        K0zZhpkkdKbSw2FAnClTzechpostQIrW+rnTABEBAAG0LHBoaWxhbmRybyBTb2Z0
        d2FyZSBHbWJIIDxpbmZvQHBoaWxhbmRyby5jb20+iQFUBBMBCAA+AhsDBQsJCAcC
        BhUICQoLAgQWAgMBAh4BAheAFiEE1WMR5f87bznVoWq+GN83Qc3/3ikFAl37dqUF
        CQeFEfcACgkQGN83Qc3/3ilrHggAo/TaU9lRW/cgTiCFWlZMxZdESh+ICUAXf3za
        RoCmGRXHfxiln2ab2jcA7RoYVWH0bD4mRDd3RmLYh297tB2DrM/Rl6BjYclALapj
        OSLAXlUHBVWwxsjwUHCukuxwflovw61+367fugTVCmfuptpVs0a06kMQMg19YruT
        lhiRTGSLzywioTIzlVECupyzh0SfUsirLmB3bz2/AQcp7K10fMzB61BYw8/+798O
        80iKWwbWmKc+6iVVQ5hVzGoki3FTa0/bMeYaDz7P6wPrlymoeDo+5dmLnA0H2Klz
        AMXQjcEuXUocUabSzqC4a7i8oj+kPX+qlwQ0XwpqSvY39zcfDrkBDQRaOMuuAQgA
        sCQfQrMKK7jfsFud7AuotHDKmjcXkHVSHgbC+jFc/+1ZbvE5FIj9QajcJ1MjWLRZ
        ytaF3z6k3CZYnDnchCNY1ygNKi8ojBIm3bSNymrgbY9JmK8DZ7ms6bCaTKmSt9rL
        PZeK9hLttPgzdreH38zz1ynDCIVmnlTHp4pexje75Ow1O/9BZpdphUHayiv2VqgN
        lWdCl85lTkDit6vEftEIeJNXyXSl4CZIO1ilMbJWKHH5x6KkCWQ3x7Zu7JbEtJdg
        hWBBw0d3QPKlbl6Dh/TpT0YhJXYfqFuXmJZDZ/mg8zIk0AZHhDjKVmhVWIJNlMnr
        3IBwqOcqOu1EpCTSTcllMwARAQABiQE8BBgBCAAmAhsMFiEE1WMR5f87bznVoWq+
        GN83Qc3/3ikFAl37drUFCQeFEgcACgkQGN83Qc3/3imLnggAljdxeldJ4e0XtAk0
        FOa18ynQ6pfb0HJsZpyutb5Yq4ZzDDqKhTAsTWq/WcFHkTsTw/FBYRsaImSspOoA
        5xW3cCF4wLiBcgPoK+58jb4JPHrB+FMgD6KDIm91e0ebXmBDyZqOnKEow38bRkdW
        GLHoDrlWwLs3eAEkUi8xurtg7Iq/S4YuqLMcZO7MrquL4niDxFoxD7aV4uZFztiS
        qwt4pJFbBgDhvX+ewwScqMcgAIISzu8WKZnHahYuHkC5nAUG5lMpIBj7tc0YTCw+
        qbWRwLm0YmUU/ZzbOdLaBKqReWCJJYGcpyMSOQ2skn9ofDjGjwtbKa6mub/V/WWI
        U1kPig==
        =MUUO
        -----END PGP PUBLIC KEY BLOCK-----

    # TODO
# intellij
# git
# lg
#
