#cloud-config

ssh_pwauth: false
package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - xubuntu-core
  - software-properties-common
  - x2goserver
  - x2goserver-xsession
  - x2goserver-desktopsharing
  - firefox
  - flatpak
  - git
  - lazygit
  - docker.io
  - python
  - python3.8
  - python3-pip
  - meld
  - curl
  - gconf2
  - apt-transport-https
    
snap:
  commands:
    - ['install', '--classic', '--channel=2021.1/stable', 'intellij-idea-ultimate']
    - ['install', '--classic', '--channel=2021.1/stable', 'rider']
    - ['install', '--classic', '--channel=2021.1/stable', 'pycharm-professional']
    - ['install', '--classic', 'code']
    - ['install', 'typora']
    - ['install', 'postman']

write_files:
  - content: |
      [Desktop Entry]
      Version=1.0
      Name=Mob Timer
      Exec=/home/mob/mob-timer-linux-x64/mob-timer
      Icon=/home/mob/mob-timer-linux-x64/resources/app/icon.ico
      Terminal=false
      Type=Application
      Categories=Application;Development
    path: /usr/share/applications/mob-timer.desktop

  - content: |
      #!/bin/bash
      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
      sudo apt update
      sudo apt install gh
    path: /opt/install-gh-cli.sh
    permissions: '0755'

  - content: |
      alias lg="lazygit"
      tdd_ts() {
        curl https://gist.githubusercontent.com/gregorriegler/5c578410a619188838d3c9c6c23e09ae/raw/66f53f19c5112e78e298ffe3cc49d3c5b0655738/tdd-bootstrap-ts-mocha-chai.sh | bash -s "$1"
      }
      tdd_js() {
        curl https://gist.githubusercontent.com/gregorriegler/3e6f5d38f74fec9f2be0c66ddf16195d/raw/d36216c683a47f72db5d4e7c8333a68066b3af60/tdd-bootstrap-js-mocha-chai.sh | bash -s "$1"
      }
    path: /opt/.bash_aliases
    permissions: '0755'

  - content: |
      #!/bin/bash
      
      launcher_plugins=()
      
      next_plugin_id () {
        local highest_number=$(xfconf-query -c xfce4-panel -p /plugins -l | cut -d"-" -f2 | cut -d"/" -f1 | sort -V -r | head -n 1)
        plugin_id=$((highest_number + 1))
      }
      
      create_launcher_plugin () {
        next_plugin_id
        mkdir ~/.config/xfce4/panel/launcher-$plugin_id
        cp $1 ~/.config/xfce4/panel/launcher-$plugin_id
        xfconf-query -c xfce4-panel -p /plugins/plugin-$plugin_id -t string -s "launcher" --create
        xfconf-query -c xfce4-panel -p /plugins/plugin-$plugin_id/items -t string -s "$(basename "${1%.*}").desktop" -a --create
        launcher_plugins+=("$plugin_id")
      }
      
      create_launcher_plugin "/usr/share/applications/firefox.desktop"
      create_launcher_plugin "/usr/share/applications/google-chrome.desktop"
      create_launcher_plugin "/var/lib/snapd/desktop/applications/intellij-idea-ultimate_intellij-idea-ultimate.desktop"
      create_launcher_plugin "/var/lib/snapd/desktop/applications/pycharm-professional_pycharm-professional.desktop"
      create_launcher_plugin "/var/lib/snapd/desktop/applications/rider_rider.desktop"
      create_launcher_plugin "/var/lib/snapd/desktop/applications/code_code.desktop"
      create_launcher_plugin "/usr/share/applications/vim.desktop"
      create_launcher_plugin "/var/lib/snapd/desktop/applications/typora_typora.desktop"
      create_launcher_plugin "/usr/share/applications/org.gnome.meld.desktop"
      create_launcher_plugin "/var/lib/snapd/desktop/applications/postman_postman.desktop"
      create_launcher_plugin "/usr/share/applications/mob-timer.desktop"
      create_launcher_plugin "/var/lib/flatpak/exports/share/applications/com.anydesk.Anydesk.desktop"
      
      plugins_string=""
      
      for plugin in "${launcher_plugins[@]}"
      do
        plugins_string="${plugins_string} -t int -s ${plugin} "
      done
      
      ## clear panel 2
      xfconf-query -c xfce4-panel -p /panels/panel-2/plugin-ids -rR
      
      ## refill panel 2
      xfconf-query -c xfce4-panel -p /panels/panel-2/plugin-ids \
              -t int -s 15 \
              -t int -s 16 \
              -t int -s 17 \
              -t int -s 18 \
              $plugins_string \
              --create
      
      ## restart panel
      xfce4-panel -r

      ## Clear Shortcuts needed by IntelliJ
      xfconf-query -c xfce4-keyboard-shortcuts -p '/xfwm4/custom/<Alt>Insert' -r -R
      xfconf-query -c xfce4-keyboard-shortcuts -p '/xfwm4/custom/<Alt>Delete' -r -R
      xfconf-query -c xfce4-keyboard-shortcuts -p '/commands/custom/<Primary><Alt>l' -r -R
      setxkbmap -option caps:escape

      ## start X2Go Desktop Sharing
      /usr/bin/x2godesktopsharing

    path: /opt/init-xfce4-panel.sh
    permissions: '0755'

  - content: |
      require('http').createServer(function (req, res) { res.end('UP'); }).listen(3000); 
    path: /opt/up.js
    permissions: '0755'

  - content: |
      #!/bin/bash

      # sdkman & java 
      curl -s "https://get.sdkman.io" | bash
      source "$HOME/.sdkman/bin/sdkman-init.sh" ; sdk install java 17.0.2-tem ; sdk install gradle ; sdk install maven

      # nvm & node
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      bash -ic "nvm install node ; npm install --global yarn"
      
      # desktop theme
      /usr/bin/xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita-dark"

      # install mob-timer
      wget "https://github.com/gregorriegler/mob-timer/releases/download/linux/mob-timer-linux-x64.zip" -O temp.zip ; unzip temp.zip ; rm temp.zip

      # Panel Shortcuts
      mkdir ~/.config/autostart
      echo -e "[Desktop Entry]\nType=Application\nExec=/opt/init-xfce4-panel.sh\nName=Init xfce4 Panel\nComment=Init xfce4 Panel" | tee > ~/.config/autostart/init-xfce4-panel.desktop

      # Dot files
      cp /opt/.bash_aliases ~/.bash_aliases

      # Kata Bootstraps
      git clone https://github.com/swkBerlin/kata-bootstraps ~/kata-bootstraps

      # Bookshelf Kata
      git clone -b no-spoilers https://github.com/gregorriegler/Bookshelf-Kata.git ~/bookshelf-kata
      
      # Kata Bootstraps
      git clone https://github.com/emilybache/GildedRose-Refactoring-Kata.git ~/gilded-rose-refactoring-kata

    path: /opt/user-scripts.sh
    permissions: '0755'

runcmd:
  - [wget, "https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb", -O, /root/packages-microsoft-prod.deb]
  - dpkg -i /root/packages-microsoft-prod.deb
  - rm /root/packages-microsoft-prod.deb
  - apt update
  - apt-get install dotnet-sdk-6.0 -y
  - usermod -aG docker mob
  - chmod 666 /var/run/docker.sock
  - apt remove -y xfce4-screensaver
  - apt remove -y xfce4-power-manager
  - apt remove -y light-locker
  - sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - systemctl restart sshd
  - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - flatpak install -y flathub com.anydesk.Anydesk
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - dpkg -i google-chrome-stable_current_amd64.deb
  - /opt/install-gh-cli.sh
  - printf "<!DOCTYPE NXKeystroke>\n<keystrokes></keystrokes>\n" > /etc/x2go/keystrokes.cfg
  - runuser -l mob -c 'bash -ic "/opt/user-scripts.sh"'
  - runuser -l mob -c 'bash -ic "node /opt/up.js &"'

apt:
  sources:
    lazygit.list:
      source: "ppa:lazygit-team/release"
    deadsnakes.list:
      source: "ppa:deadsnakes/ppa"

# TODO
# Extract all runuser to its own script
# anydesk password ?
# zsh + plugins
# automatically destroy after 4 inactive hours
#
#
# Tips:
# Anydesk:
# Show remote Cursor
# Give up Mouse+Keyboard Control
# Hetzner
# test
