#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - xubuntu-core
  - software-properties-common
  - x2goserver
  - x2goserver-xsession
  - x2goserver-desktopsharing
  - firefox
  - flatpak
  - git
  - lazygit
  - docker.io
  - python
  - python3.8
  - python3-pip
  - meld
  - curl
  - gconf2
    
snap:
  commands:
    - ['install', '--classic', '--edge', 'intellij-idea-ultimate']
    - ['install', '--classic', 'code']

write_files:
  - content: |
      [Desktop Entry]
      Version=1.0
      Name=Mob Timer
      Exec=/home/gregor/mob-timer-linux-x64/mob-timer
      Icon=/home/gregor/mob-timer-linux-x64/resources/app/icon.ico
      Terminal=false
      Type=Application
      Categories=Application;Development
    path: /usr/share/applications/mob-timer.desktop
  - content: |
      #!/bin/bash
      
      launcher_plugins=()
      
      next_plugin_id () {
        local highest_number=$(xfconf-query -c xfce4-panel -p /plugins -l | cut -d"-" -f2 | cut -d"/" -f1 | sort -V -r | head -n 1)
        plugin_id=$((highest_number + 1))
      }
      
      create_launcher_plugin () {
        next_plugin_id
        mkdir ~/.config/xfce4/panel/launcher-$plugin_id
        cp $1 ~/.config/xfce4/panel/launcher-$plugin_id
        xfconf-query -c xfce4-panel -p /plugins/plugin-$plugin_id -t string -s "launcher" --create
        xfconf-query -c xfce4-panel -p /plugins/plugin-$plugin_id/items -t string -s "$(basename "${1%.*}").desktop" -a --create
        launcher_plugins+=("$plugin_id")
      }
      
      create_launcher_plugin "/usr/share/applications/firefox.desktop"
      create_launcher_plugin "/usr/share/applications/google-chrome.desktop"
      create_launcher_plugin "/var/lib/snapd/desktop/applications/intellij-idea-ultimate_intellij-idea-ultimate.desktop"
      create_launcher_plugin "/var/lib/snapd/desktop/applications/code_code.desktop"
      create_launcher_plugin "/usr/share/applications/vim.desktop"
      create_launcher_plugin "/usr/share/applications/org.gnome.meld.desktop"
      create_launcher_plugin "/usr/share/applications/mob-timer.desktop"
      create_launcher_plugin "/var/lib/flatpak/exports/share/applications/com.anydesk.Anydesk.desktop"
      
      plugins_string=""
      
      for plugin in "${launcher_plugins[@]}"
      do
        plugins_string="${plugins_string} -t int -s ${plugin} "
      done
      
      ## clear panel 2
      xfconf-query -c xfce4-panel -p /panels/panel-2/plugin-ids -rR
      
      ## refill panel 2
      xfconf-query -c xfce4-panel -p /panels/panel-2/plugin-ids \
              -t int -s 15 \
              -t int -s 16 \
              -t int -s 17 \
              -t int -s 18 \
              $plugins_string \
              --create
      
      ## restart panel
      xfce4-panel -r
    path: /opt/init-xfce4-panel.sh
    permissions: '0755'

runcmd:
  - usermod -aG docker gregor
  - chmod 666 /var/run/docker.sock
  - apt remove -y xfce4-screensaver
  - apt remove -y xfce4-power-manager
  - apt remove -y light-locker
  - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - flatpak install -y flathub com.anydesk.Anydesk
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - dpkg -i google-chrome-stable_current_amd64.deb
  - runuser -l gregor -c 'curl -s "https://get.sdkman.io" | bash'
  - runuser -l gregor -c 'source "$HOME/.sdkman/bin/sdkman-init.sh" ; sdk install java ; sdk install gradle ; sdk install maven'
  - runuser -l gregor -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash'
  - runuser -l gregor -c 'bash -ic "nvm install node ; npm install --global yarn"'
  - runuser -l gregor -c '/usr/bin/xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita-dark"'
  - runuser -l gregor -c 'wget "https://github.com/gregorriegler/mob-timer/releases/download/linux/mob-timer-linux-x64.zip" -O temp.zip ; unzip temp.zip ; rm temp.zip'
  - runuser -l gregor -c 'echo -e "[Desktop Entry]\nType=Application\nExec=/opt/init-xfce4-panel.sh\nName=Init xfce4 Panel\nComment=Init xfce4 Panel" | tee > ~/.config/autostart/init-xfce4-panel.desktop'
    
apt:
  sources:
    lazygit.list:
      source: "ppa:lazygit-team/release"
    deadsnakes.list:
      source: "ppa:deadsnakes/ppa"

# TODO
# intellij k
# Xscreensaver k
# vscode k
# git k
# lg k
# sdkman k
# jdk k
# maven k
# gradle k
# nvm k
# node+npm k
# yarn k
# melddiff k
# mob-timer k
# google-chrome-stable k
# power management off k
# docker k
# python k
# pip k
# dark terminal k 
# dark layout k 
# 30 min no freeze test k
# caps -> escape
# github-cli
# zsh + plugins
# vpn ?
# anydesk password ?
#
# Tips:
# Anydesk:
# Show remote Cursor
# Give up Mouse+Keyboard Control
# Hetzner
