#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - xubuntu-core
  - software-properties-common
  - x2goserver
  - x2goserver-xsession
  - x2goserver-desktopsharing
  - firefox
  - flatpak
  - git
  - lazygit
  - docker.io
  - python
  - python3.8
  - python3-pip
  - meld
  - curl
  - gconf2
    
snap:
  commands:
    - ['install', '--classic', '--edge', 'intellij-idea-ultimate']
    - ['install', '--classic', 'code']

write_files:
  - content: |
      [Desktop Entry]
      Version=1.0
      Name=Mob Timer
      Exec=/home/gregor/mob-timer-linux-x64/mob-timer
      Icon=/home/gregor/mob-timer-linux-x64/resources/app/icon.ico
      Terminal=false
      Type=Application
      Categories=Application;Development
    path: /usr/share/applications/mob-timer.desktop
      
runcmd:
  - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - flatpak install -y flathub com.anydesk.Anydesk
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - dpkg -i google-chrome-stable_current_amd64.deb
  - apt remove -y xfce4-screensaver
  - apt remove -y xfce4-power-manager
  - runuser -l gregor -c 'curl -s "https://get.sdkman.io" | bash'
  - runuser -l gregor -c 'source "$HOME/.sdkman/bin/sdkman-init.sh" ; sdk install java ; sdk install gradle ; sdk install maven'
  - runuser -l gregor -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash'
  - runuser -l gregor -c 'bash -ic "nvm install node ; npm install --global yarn"'
  - usermod -aG docker gregor
  - chmod 666 /var/run/docker.sock
  - runuser -l gregor -c '/usr/bin/xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita-dark"'
  - runuser -l gregor -c 'wget "https://github.com/gregorriegler/mob-timer/releases/download/linux/mob-timer-linux-x64.zip" -O temp.zip ; unzip temp.zip ; rm temp.zip'
    
apt:
  sources:
    lazygit.list:
      source: "ppa:lazygit-team/release"
    deadsnakes.list:
      source: "ppa:deadsnakes/ppa"

# intellij k
# Xscreensaver k
# vscode k
# git k
# lg k
# sdkman k
# jdk k
# maven k
# gradle k
# nvm k
# node+npm k
# yarn k
# zsh + plugins
# melddiff k
# github-cli
# mob-timer k
# google-chrome-stable k
# vpn ?
# anydesk password ?
# power management off k
# docker k
# python k
# pip k
# dark layout k 
#
# Tips:
# Anydesk:
# Show remote Cursor
# Give up Mouse+Keyboard Control
# Hetzner
